#Application Configuration
#Mon Sep 29 16:42:53 EDT 2025
company.address=123 Main Street, Charleroi, PA
company.logo.path=file\:/C\:/Users/chris/Downloads/ChatGPT%20Image%20May%2022,%202025,%2006_44_27%20PM.png
company.name=Marsh Tire & Service Inc
company.phone=724-483-8851
credit.card.fee.percentage=0.00
inventory.default.lowstock.threshold=5
role.permission.ADMIN=Services,Sales,Customers,Appointments,Reports,Admin Settings,Inventory
role.permission.FRONT_DESK=Services,Sales,Customers,Appointments,Inventory
role.permission.MANAGER=Services,Sales,Customers,Appointments,Reports,Inventory
role.permission.TECHNICIAN=Services,Appointments
sales.tax.rate=0.06
tire.api.lookup.enabled=false
