#Application Configuration
#Fri May 16 21:23:39 EDT 2025
company.address=123 Main Street, Charleroi, PA
credit.card.fee.percentage=0.02
sales.tax.rate=0.06
company.phone=724-483-8851
company.logo.path=
inventory.default.lowstock.threshold=5
company.name=Marsh Tire & Service Inc
